//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public string TransId { get; set; }
        public string IpAdress { get; set; }
        public string TransType { get; set; }
        public int Id { get; set; }
        public string Message { get; set; }
        public string TimeStamp { get; set; }
        public string UserIp { get; set; }
    }
}
