//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEquip
    {
        public int UserId { get; set; }
        public Nullable<int> WeaponId { get; set; }
        public Nullable<int> SecondWeaponId { get; set; }
        public Nullable<int> HelmetId { get; set; }
        public Nullable<int> UpperId { get; set; }
        public Nullable<int> LowerId { get; set; }
        public Nullable<int> GlovesId { get; set; }
        public Nullable<int> ShoesId { get; set; }
        public Nullable<int> Ring1Id { get; set; }
        public Nullable<int> Ring2Id { get; set; }
        public Nullable<int> Earring1Id { get; set; }
        public Nullable<int> Earring2Id { get; set; }
        public Nullable<int> AmuletId { get; set; }
        public Nullable<int> BeltId { get; set; }
        public Nullable<int> CloakId { get; set; }
    
        public virtual User User { get; set; }
    }
}
