//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string LoginName { get; set; }
        public byte[] PasswordHash { get; set; }
        public System.Guid Salt { get; set; }
        public string Email { get; set; }
    
        public virtual GeneralStats GeneralStats { get; set; }
    }
}
