//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthorizationLog
    {
        public int RowId { get; set; }
        public string UserLogin { get; set; }
        public string IpAdress { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public byte OpResult { get; set; }
        public string Message { get; set; }
    }
}
