//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbEntities1 : DbContext
    {
        public TestDbEntities1()
            : base("name=TestDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<BannedAccount> BannedAccount { get; set; }
        public virtual DbSet<TestTable> TestTable { get; set; }
        public virtual DbSet<TestTable2> TestTable2 { get; set; }
        public virtual DbSet<TestTable3> TestTable3 { get; set; }
    }
}
