
CREATE TABLE dbo.GeneralStats
(	
	UserId INT PRIMARY KEY,
	[Exp] INT DEFAULT 0,
	[ReqExp] INT DEFAULT 10,
	[Lvl] INT DEFAULT 1,
	Hp INT DEFAULT 10,
	AP INT DEFAULT 10,
	Dp INT DEFAULT 10,
	Steps INT DEFAULT 30,
	Fp INT DEFAULT 15,
	Gold INT DEFAULT 0,
	FOREIGN KEY (UserId) REFERENCES dbo.[User] (UserId),


)